image: mcr.microsoft.com/dotnet/sdk:5.0

stages:
  - build
  - test
  - documentation

build-all:
  stage: build
  script:
    - echo "Debug build..."
    - dotnet build
  
run-unit-tests:
  stage: test 
  script:
    - echo "Running unit tests..."
    - dotnet test

generate-documentation:
  stage: documentation
  image: alpine
  script:
  - apk update && apk add doxygen
  - doxygen Doxyfile
  - mkdir public
  - mv html public/
  - mv latex public/
  artifacts:
    paths:
    - public
  only:
  - master