image: mcr.microsoft.com/dotnet/sdk:5.0

stages:
  - build
  - test

before_script:
  - "dotnet restore"

build:
  stage: build
  script:
    - "cd lib/ArgParser"
    - "dotnet build"

test:
  stage: test
  script:
    - "cd APITester"
    - "dotnet test"